//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1.Properties {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("_1.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap _01 {
            get {
                object obj = ResourceManager.GetObject("_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap _02 {
            get {
                object obj = ResourceManager.GetObject("_02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap _03 {
            get {
                object obj = ResourceManager.GetObject("_03", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap _04 {
            get {
                object obj = ResourceManager.GetObject("_04", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap _05 {
            get {
                object obj = ResourceManager.GetObject("_05", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap _06 {
            get {
                object obj = ResourceManager.GetObject("_06", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap _07 {
            get {
                object obj = ResourceManager.GetObject("_07", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap _08 {
            get {
                object obj = ResourceManager.GetObject("_08", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap _09 {
            get {
                object obj = ResourceManager.GetObject("_09", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap _1 {
            get {
                object obj = ResourceManager.GetObject("_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap _10 {
            get {
                object obj = ResourceManager.GetObject("_10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap _11 {
            get {
                object obj = ResourceManager.GetObject("_11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap _12 {
            get {
                object obj = ResourceManager.GetObject("_12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap _13 {
            get {
                object obj = ResourceManager.GetObject("_13", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap _14 {
            get {
                object obj = ResourceManager.GetObject("_14", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap _2 {
            get {
                object obj = ResourceManager.GetObject("_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap _3 {
            get {
                object obj = ResourceManager.GetObject("_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap _4 {
            get {
                object obj = ResourceManager.GetObject("_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap _5 {
            get {
                object obj = ResourceManager.GetObject("_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap _6 {
            get {
                object obj = ResourceManager.GetObject("_6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap cat {
            get {
                object obj = ResourceManager.GetObject("cat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Image1 {
            get {
                object obj = ResourceManager.GetObject("Image1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Image2 {
            get {
                object obj = ResourceManager.GetObject("Image2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap open {
            get {
                object obj = ResourceManager.GetObject("open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap rob {
            get {
                object obj = ResourceManager.GetObject("rob", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap sp {
            get {
                object obj = ResourceManager.GetObject("sp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 0.017453293
        ///-0.266205502
        ///-0.222298872
        ///-0.186669627
        ///-0.162290736
        ///-0.145987356
        ///-0.135074809
        ///-0.127408575
        ///-0.121312187
        ///-0.115510268
        ///-0.109068703
        ///-0.101341423
        ///-0.091923213
        ///-0.080608003
        ///-0.067352105
        ///-0.052241891
        ///-0.035465468
        ///-0.017287927
        ///0.001970213
        ///0.021951692
        ///0.042278627
        ///0.062566329
        ///0.082435045
        ///0.101519827
        ///0.119478711
        ///0.135999368
        ///0.150804355
        ///0.163655105
        ///0.174354766
        ///0.182749988
        ///0.188731765
        ///0.192235411
        ///0.193239767
        ///0.191765716
        ///0.187874089
        ///0.181663032
        ///0.173264927
        ///0.162842925
        ///0 [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string test1 {
            get {
                return ResourceManager.GetString("test1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 0.017453293
        ///0.017530963
        ///0.016874045
        ///0.015960958
        ///0.014889434
        ///0.013729351
        ///0.012533916
        ///0.011342901
        ///0.010185238
        ///0.009081195
        ///0.008044189
        ///0.007082289
        ///0.006199452
        ///0.00539653
        ///0.00467209
        ///0.00402307
        ///0.003445299
        ///0.002933908
        ///0.002483649
        ///0.002089133
        ///0.001745011
        ///0.001446109
        ///0.00118751
        ///0.00096462
        ///0.000773201
        ///0.000609385
        ///0.000469676
        ///0.000350943
        ///0.000250402
        ///0.000165597
        ///9.43728E-05
        ///3.4851E-05
        ///-1.45969E-05
        ///-5.53759E-05
        ///-8.86923E-05
        ///-0.000115578
        ///-0.000136913
        ///-0.000153445
        ///-0.00016581
        ///-0.00 [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string test2 {
            get {
                return ResourceManager.GetString("test2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 0.017453293
        ///-1.343046301
        ///-1.074176259
        ///-0.848794591
        ///-0.685873252
        ///-0.571458371
        ///-0.493414444
        ///-0.44178596
        ///-0.408499573
        ///-0.387088289
        ///-0.372448703
        ///-0.360628611
        ///-0.348642113
        ///-0.334309328
        ///-0.31611806
        ///-0.293104852
        ///-0.264753107
        ///-0.230906128
        ///-0.191693158
        ///-0.147466659
        ///-0.098749323
        ///-0.046189411
        ///0.009476736
        ///0.06745608
        ///0.126925062
        ///0.187051336
        ///0.247011734
        ///0.306007027
        ///0.363273958
        ///0.418094961
        ///0.469805885
        ///0.517802032
        ///0.561542726
        ///0.600554618
        ///0.634433897
        ///0.662847526
        ///0.68553364
        ///0.702301178
        ///0 [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string test3 {
            get {
                return ResourceManager.GetString("test3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 0.017453293
        ///0.833907479
        ///0.671525055
        ///0.534826742
        ///0.435352795
        ///0.36484245
        ///0.316099313
        ///0.283213515
        ///0.261387173
        ///0.246772376
        ///0.236328427
        ///0.227696813
        ///0.219092234
        ///0.209208055
        ///0.197134604
        ///0.182288854
        ///0.164354131
        ///0.143228591
        ///0.118981349
        ///0.091815238
        ///0.062035292
        ///0.03002217
        ///-0.003790203
        ///-0.03893337
        ///-0.074919988
        ///-0.111256848
        ///-0.147455648
        ///-0.18304187
        ///-0.217562017
        ///-0.250589488
        ///-0.281729242
        ///-0.310621471
        ///-0.336944377
        ///-0.360416201
        ///-0.380796589
        ///-0.397887371
        ///-0.411532835
        ///-0.421619543
        ///-0.428 [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string test4 {
            get {
                return ResourceManager.GetString("test4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 0
        ///0.034360401
        ///0.038311948
        ///0.042502167
        ///0.047449739
        ///0.053049347
        ///0.059182172
        ///0.065729044
        ///0.072571833
        ///0.079594612
        ///0.086684821
        ///0.093734384
        ///0.100640787
        ///0.107308083
        ///0.113647806
        ///0.119579791
        ///0.125032868
        ///0.129945444
        ///0.134265943
        ///0.137953117
        ///0.14097621
        ///0.143314989
        ///0.144959629
        ///0.145910476
        ///0.146177671
        ///0.145780662
        ///0.144747605
        ///0.143114665
        ///0.140925232
        ///0.138229067
        ///0.13508138
        ///0.131541875
        ///0.127673756
        ///0.123542723
        ///0.119215963
        ///0.114761155
        ///0.110245506
        ///0.105734818
        ///0.101292614
        ///0.096979316
        ///0.09 [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string testtheta {
            get {
                return ResourceManager.GetString("testtheta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 0
        ///-3.85288E-05
        ///-3.87341E-05
        ///-3.62157E-05
        ///-3.2763E-05
        ///-2.8965E-05
        ///-2.5239E-05
        ///-2.18844E-05
        ///-1.91067E-05
        ///-1.70354E-05
        ///-1.57404E-05
        ///-1.52445E-05
        ///-1.55343E-05
        ///-1.65694E-05
        ///-1.82892E-05
        ///-2.06194E-05
        ///-2.34763E-05
        ///-2.67709E-05
        ///-3.04118E-05
        ///-3.43078E-05
        ///-3.83699E-05
        ///-4.25122E-05
        ///-4.66535E-05
        ///-5.07178E-05
        ///-5.46353E-05
        ///-5.83421E-05
        ///-6.17809E-05
        ///-6.49013E-05
        ///-6.7659E-05
        ///-7.00168E-05
        ///-7.19437E-05
        ///-7.34149E-05
        ///-7.44119E-05
        ///-7.49221E-05
        ///-7.49383E-05
        ///-7.44589E-05
        ///-7.34872E-05
        ///-7.20312E [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string testtheta2 {
            get {
                return ResourceManager.GetString("testtheta2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 0
        ///0.165045
        ///0.177760574
        ///0.190409665
        ///0.205990989
        ///0.224260137
        ///0.244909365
        ///0.267631835
        ///0.29212298
        ///0.318080913
        ///0.345207065
        ///0.373207047
        ///0.40179171
        ///0.430678337
        ///0.459591951
        ///0.488266687
        ///0.516447201
        ///0.543890082
        ///0.57036524
        ///0.595657232
        ///0.619566516
        ///0.641910605
        ///0.6625251
        ///0.681264592
        ///0.698003413
        ///0.712636235
        ///0.725078499
        ///0.735266677
        ///0.743158356
        ///0.748732157
        ///0.751987468
        ///0.752944023
        ///0.751641299
        ///0.748137777
        ///0.742510035
        ///0.734851714
        ///0.725272352
        ///0.713896106
        ///0.700860364
        ///0.68631428
        ///0.670417226 [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string testtheta3 {
            get {
                return ResourceManager.GetString("testtheta3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 0
        ///-0.099087664
        ///-0.106716417
        ///-0.114301538
        ///-0.123644579
        ///-0.134599755
        ///-0.14698305
        ///-0.160610813
        ///-0.17530062
        ///-0.190871539
        ///-0.207144538
        ///-0.223943026
        ///-0.241093494
        ///-0.258426256
        ///-0.275776235
        ///-0.2929838
        ///-0.309895618
        ///-0.326365509
        ///-0.342255277
        ///-0.357435518
        ///-0.37178637
        ///-0.385198211
        ///-0.397572276
        ///-0.408821206
        ///-0.418869493
        ///-0.427653845
        ///-0.435123443
        ///-0.441240095
        ///-0.445978292
        ///-0.449325154
        ///-0.451280275
        ///-0.451855461
        ///-0.451074383
        ///-0.448972116
        ///-0.445594607
        ///-0.440998049
        ///-0.435248181
        ///-0.4284195 [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string testtheta4 {
            get {
                return ResourceManager.GetString("testtheta4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Byte[] 的當地語系化資源。
        /// </summary>
        internal static byte[] 車子 {
            get {
                object obj = ResourceManager.GetObject("車子", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap 車子1 {
            get {
                object obj = ResourceManager.GetObject("車子1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap 輪子 {
            get {
                object obj = ResourceManager.GetObject("輪子", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
